services:
  postgres:
    image: postgres:16
    container_name: CI_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - CI_network

  backend:
    build: .
    container_name: CI_backend
    depends_on:
       - postgres

    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRETKEY: ${SECRETKEY}
    ports:
      - "5000:8080"
    command: [ "dotnet", "TestCI.dll" ]
    networks:
      - CI_network
  
  frontend:
      image: nginx:alpine
      container_name: CI_frontend
      restart: always
      ports:
        - "80:80"
      volumes:
        # Монтируем исходники фронтенда в стандартную папку Nginx
        - ./frontend:/usr/share/nginx/html:ro
        # Монтируем конфигурацию Nginx
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - backend
      networks:
        - CI_network


networks:
  CI_network:

volumes:
  postgres_data: