server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 1. Запросы к статике (js, css, svg, png и т.д.)
    # Если файла нет — отдаем честный 404, а не index.html!
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        try_files $uri =404;
        expires max;
        access_log off;
    }

    # 2. Роутинг для SPA (все HTML-переходы)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 3. Бэкенд API
    location /api/ {
        proxy_pass http://backend:8080/api/;
    }
}