// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestCI.Infrastructure.Persistence;

#nullable disable

namespace TestCI.Migrations
{
    [DbContext(typeof(DigiRubContext))]
    partial class DigiRubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "status_wallet", new[] { "Prcs", "Actv", "Blck", "Clsd" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestCI.Domain.Authentification.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex(new[] { "Token" }, "refresh_tokens_token_key")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TestCI.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Mid")
                        .HasColumnType("uuid")
                        .HasColumnName("mid");

                    b.Property<string>("FisrtName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fisrt_name");

                    b.Property<Guid?>("IdDr")
                        .HasColumnType("uuid")
                        .HasColumnName("id_dr");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("middle_name");

                    b.HasKey("Mid")
                        .HasName("clients_pkey");

                    b.HasIndex(new[] { "IdDr" }, "clients_id_dr_key")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("TestCI.Domain.DrWallets.DrWallet", b =>
                {
                    b.Property<Guid>("Id_DRw")
                        .HasColumnType("uuid")
                        .HasColumnName("id_drw");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_bill");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid?>("ClientMid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("status_wallet")
                        .HasColumnName("status_wallet");

                    b.HasKey("Id_DRw")
                        .HasName("dr_wallet_pkey");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientMid");

                    b.HasIndex(new[] { "BillId" }, "dr_wallet_id_bill_key")
                        .IsUnique();

                    b.ToTable("dr_wallet", (string)null);
                });

            modelBuilder.Entity("TestCI.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_user_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Login" }, "users_user_login_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TestCI.Models.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ChangedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by")
                        .HasDefaultValueSql("CURRENT_USER");

                    b.Property<string>("NewData")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_data");

                    b.Property<string>("OldData")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_data");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("operation");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name");

                    b.HasKey("Id")
                        .HasName("logs_pkey");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("TestCI.Domain.DrWallets.DrWallet", b =>
                {
                    b.HasOne("TestCI.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("dr_wallet_client_id_fkey");

                    b.HasOne("TestCI.Domain.Clients.Client", null)
                        .WithMany("DrWallets")
                        .HasForeignKey("ClientMid");
                });

            modelBuilder.Entity("TestCI.Domain.Clients.Client", b =>
                {
                    b.Navigation("DrWallets");
                });
#pragma warning restore 612, 618
        }
    }
}
